export const  sidebar_home_icon = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR75_v-te2LMN2SYKNo5wlIm6XBACW75i-ww&s"
export const hamburger_icon_header = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw9Mu4yCMe-nK3QxKol2x4cCia-nTqJu-PCA&s"
export const youtube_logo_header = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBaCgGJcTwKX5EYMuhYd3xuGQHUDo6wq07MQ&s"
export const bell_icon_header = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrTiUrVaXOHR6zxamtHVpKkRmFm2H2a0rdbg&s"
export const user_avatr_icon = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLtKkOaBtdg8WrVMovsDXKVlE_7PWTdfnjrg&s"
export const mic_icon_header = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWvkm-IIm70JONUoXGgJxI08erSIFmgtj_vA&s"
export const search_icon_header = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf8E-ADHCUm0aVqpN5TmbJxdE1CLNw50o5JA&s"
